- 404.html
> fix 404 link

- index.html
Typo on download link for NanoPiM4V2
> Typo on download link

- .github/workflows/main.yml
Makes us independent from wrapping GitHub action and more control over PySpelling environment and arguments.
Additionally separate liche install and actual link checks to cleanup/sort results and allow better review.
> Install and run PySpelling manually

- .github/workflows/main.yml
- dietpi-software.html
- images/dietpi-logo_mask_720x720.svg
This gives us better control and flexibility and probably reduces overhead.
> Install and run html5validator manually

- index.html
See https://github.com/MichaIng/DietPi-Website/issues/15.
> Switch links from https://dietpi.com/#features to new DietPi docs page

- dietpi-software.html
First commit for testing links.
> New links to docs instead phpBB

- dietpi-software.html
@MichaIng: Please check all links.  
Some of the links (e.g. webservers) could not be updated due no description ported yet.
> New links to docs instead to phpBB

- dietpi-software.html
Include links of the webservers to the documentation.
> Include webserver links to documentation

- index.html
Add a new banner for new version. Please adjust the text as needed.
> Add banner version 6.34

- dietpi-software.html
> Change package name to "Single File PHP Gallery"

- dietpi-contribute.html
- index.html
PR: https://github.com/MichaIng/DietPi-Website/issues/26
**Note:** initial & draft version ! Even if this pull request will be committed on the _dev_ branch, it is still a draft.
> [Draft] initial version of the dietpi-contribute page

- index.html
Instead of promoting the old release, let's promote the beta.
> Add DietPi v7.2 Beta slide

- .wordlist.txt
- index.html
Update Banner to advertise DietPi v7.3 beta
> Release week 24

- index.html
> small updates to banner (version 7.4)

- contribute.html
- css/jquery.cslider.css
- css/style.css
- dietpi-software.html
- index.html
- js/app.js
- js/jquery.cslider.js
- stats.html
> Switch to GPU accelerated translate animation

- js/jquery.cslider.js
Further slider enhancements and documentation.
Three breaking changes:
- The "page()" function has been removed, which was used by the animation dots only, which call "_navigate()" now directly and hence align much more with the navigation error click functions. This makes the index check obsolete.
- The "_navigate()" function now requires the direction, given via second argument. This was optional and calculated within the "page()" function before. Now it is done within the dots click function. This again aligns them better, as the arrow click functions calculate the target page instead.
- The "logError()" function has been removed. We use this module in our known environment, where a console is assured to be present, which makes the check for it obsolete.
> Release week 31

- contribute.html
The style has been aligned with the one from the main index page and the stats page, with a full-width header and the image right to the text.
> Adjust Brave Rewards link and portfolio frame style

- contribute.html
- dietpi-software.html
- index.html
- stats.html
On different html pages were different navigation bars.
> Correct website navigation bar contents

- index.html
Native PC image downloads changed to Bullseye.
> Release week 33.1

- index.html
Update the message on front banner
> Release week 45

- index.html
This is PR is more a suggestion
> Release banner - small change

- README.md
- deploy.bash
- js/mixitup.js
No content changes, only asset updates
> Release week 48

- index.html
A small one, I kept it simple and only changed the necessary up from the beta. Feel free to tweak the text 🙂.
> Update slider for v7.9 release

- index.html
Addresses: https://github.com/MichaIng/DietPi-Website/issues/182
> Replace crude wording with an extended sentence

- index.html
which fits better when talking about x86 systems instead of SD cards.
> Change "flash" to "write"

- .github/workflows/main.yml
- index.html
Also exclude Twitter from link check since it currently fails in general with lychee for some reason: https://github.com/lycheeverse/lychee/issues/484
> Update website banner for Beta v8.1 (#194)

- .wordlist.txt
- index.html
The docs need to be merged and deployed first: https://github.com/MichaIng/DietPi-Docs/pull/681
> Update slider for DietPi v8.1 release

- .wordlist.txt
- css/style.css
- index.html
I built the website to test URL. It is functional, but probably looks a little crowded now. I'm open for suggestions about how to enhance the style, but IMO nothing urgent.
> Add SHA256 and signature download links

- dietpi-software.html
Remove some obsolete pros/cons (we want to remove all of them, probably converting into facts in description), leave the "joke" ones. Update some info.
> Update some info

- contribute.html
> Changed contribution description to remove outdated date information

- index.html
NEO3 and R2S only have 1,296 GHz clock frequency.
> Clock frequency NanoPi R2S and NEO3 corrected

- index.html
I was just looking what alternatives are out there for the RPi 5 and I stumbled over the Rock Pi 5 family. They also have NVME M.2 slots like the 3A, so it's worth mentioning it also.
> added info for ROCK 5B model
